import { useRouter } from "expo-router";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { Button, Card, Chip, Container, Eyebrow, Field, Heading, Screen } from "@/components/ui";
import { useRecovery } from "@/context/RecoveryContext";
import { colors, spacing } from "@/theme";
import { TRIGGERS, type Mood, type Outcome, type Trigger } from "@/types/recovery";

export default function NewUrgeScreen() { const router = useRouter(); const { addUrge } = useRecovery(); const [intensity, setIntensity] = useState(5); const [trigger, setTrigger] = useState<Trigger>("Stress"); const mood: Mood = 3; const [location, setLocation] = useState(""); const [action, setAction] = useState(""); const [outcome, setOutcome] = useState<Outcome>("defeated"); const [notes, setNotes] = useState(""); const submit = () => { addUrge({ intensity, trigger, mood, location, actionTaken: action, outcome, notes }); router.back(); }; return <Screen><Container><Eyebrow>Urge tracker</Eyebrow><Heading>Capture the signal.</Heading><Card><Text style={styles.label}>Intensity</Text><View style={styles.row}>{[0, 2, 4, 6, 8, 10].map((value) => <Chip key={value} selected={intensity === value} onPress={() => setIntensity(value)}>{value}</Chip>)}</View><Text style={styles.label}>Trigger</Text><View style={styles.chips}>{TRIGGERS.map((item) => <Chip key={item} selected={trigger === item} onPress={() => setTrigger(item)}>{item}</Chip>)}</View><Text style={styles.label}>Outcome</Text><View style={styles.chips}>{(["defeated", "passed", "ongoing", "relapse"] as Outcome[]).map((item) => <Chip key={item} selected={outcome === item} onPress={() => setOutcome(item)}>{item}</Chip>)}</View><Field label="Location" value={location} onChangeText={setLocation} placeholder="Where were you?" /><Field label="Action taken" value={action} onChangeText={setAction} placeholder="Walked, breathed, called someone..." /><Field label="Notes" value={notes} onChangeText={setNotes} multiline numberOfLines={4} /><Button onPress={submit}>Save urge</Button><Button variant="ghost" onPress={() => router.back()}>Cancel</Button></Card></Container></Screen>; }
const styles = StyleSheet.create({ label: { color: colors.muted, fontSize: 13, fontWeight: "600", marginBottom: spacing.sm }, row: { flexDirection: "row", flexWrap: "wrap", marginBottom: spacing.md }, chips: { flexDirection: "row", flexWrap: "wrap", marginBottom: spacing.md } });
