import { useRouter } from "expo-router";
import { useState } from "react";
import { Alert, StyleSheet, Text } from "react-native";
import { Button, Card, Container, Eyebrow, Field, Heading, Screen } from "@/components/ui";
import { useAuth } from "@/context/AuthContext";
import { colors, spacing } from "@/theme";

export default function AuthScreen() { const router = useRouter(); const { signIn, signUp, resetPassword, configured } = useAuth(); const [mode, setMode] = useState<"signIn" | "signUp">("signIn"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const submit = async () => { const error = mode === "signIn" ? await signIn(email, password) : await signUp(email, password); if (error) Alert.alert("Could not continue", error); else { Alert.alert(mode === "signUp" && configured ? "Check your inbox" : "Welcome back", mode === "signUp" && configured ? "Confirm your email, then sign in." : "Your session is ready."); router.back(); } }; const forgot = async () => { const error = await resetPassword(email); Alert.alert(error ? "Could not send reset" : "Reset email requested", error ?? "Check your inbox for the password reset link."); }; return <Screen><Container style={styles.container}><Eyebrow>Private account</Eyebrow><Heading>{mode === "signIn" ? "Welcome back." : "Start your account."}</Heading><Text style={styles.copy}>{configured ? "Your web and iPhone data will use the same Supabase account." : "Demo mode is active. Add Supabase public variables when you are ready to sync."}</Text><Card><Field label="Email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="you@example.com" /><Field label="Password" secureTextEntry value={password} onChangeText={setPassword} placeholder="At least 8 characters" /><Button onPress={submit}>{mode === "signIn" ? "Sign in" : "Create account"}</Button>{mode === "signIn" && <Button variant="ghost" onPress={forgot}>Forgot password?</Button>}<Button variant="secondary" onPress={() => setMode(mode === "signIn" ? "signUp" : "signIn")}>{mode === "signIn" ? "Create a new account" : "I already have an account"}</Button></Card></Container></Screen>; }
const styles = StyleSheet.create({ container: { paddingTop: spacing.xxl }, copy: { color: colors.muted, fontSize: 15, lineHeight: 23, marginBottom: spacing.lg } });
