import { useRouter } from "expo-router";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { Button, Card, Chip, Container, Eyebrow, Heading, Screen, Body } from "@/components/ui";
import { useRecovery } from "@/context/RecoveryContext";
import { colors, spacing } from "@/theme";
import { TRIGGERS, type Outcome, type Trigger } from "@/types/recovery";

const actions = ["Move", "Breathe", "Reset", "Distract", "Accountability"];
export default function SosScreen() {
  const router = useRouter(); const { addUrge, addRelapse } = useRecovery(); const [step, setStep] = useState(1); const [intensity, setIntensity] = useState(5); const [trigger, setTrigger] = useState<Trigger>("Stress"); const [action, setAction] = useState(actions[0]); const [outcome, setOutcome] = useState<Outcome | null>(null);
  const finish = (result: Outcome) => { setOutcome(result); if (result === "relapse") addRelapse({ trigger, mood: 3, environment: "SOS mode", notes: "Logged from SOS mode.", reflection: "What support would make the next moment easier?" }); else addUrge({ intensity, trigger, location: "", mood: 3, actionTaken: action, outcome: result, notes: "Logged from SOS mode." }); setStep(4); };
  return <Screen><Container style={styles.container}><View style={styles.top}><Eyebrow>SOS mode · step {step} of 4</Eyebrow><Heading>{step === 4 ? "You took action." : "Let&apos;s work with this moment."}</Heading><Body muted>{step === 4 ? "This event is part of your data, not a verdict on you." : "Stay with the next small step. No judgment required."}</Body></View><Card style={styles.card}>{step === 1 && <><Heading size="small">How strong is the urge?</Heading><Text style={styles.intensity}>{intensity}<Text style={styles.outOf}> / 10</Text></Text><View style={styles.scale}>{[0, 2, 4, 6, 8, 10].map((value) => <Chip key={value} selected={intensity === value} onPress={() => setIntensity(value)}>{value}</Chip>)}</View><Button onPress={() => setStep(2)}>Continue</Button></>}{step === 2 && <><Heading size="small">What is the strongest signal?</Heading><View style={styles.chips}>{TRIGGERS.slice(0, 8).map((item) => <Chip key={item} selected={trigger === item} onPress={() => setTrigger(item)}>{item}</Chip>)}</View><Button onPress={() => setStep(3)}>Continue</Button></>}{step === 3 && <><Heading size="small">Choose one immediate action.</Heading><Body muted>Change your environment or attention for the next five minutes.</Body><View style={styles.chips}>{actions.map((item) => <Chip key={item} selected={action === item} onPress={() => setAction(item)}>{item}</Chip>)}</View><Button onPress={() => finish("defeated")}>I did it</Button><Button variant="secondary" onPress={() => finish("passed")}>It passed naturally</Button><Button variant="ghost" onPress={() => finish("relapse")}>Log a relapse respectfully</Button></>}{step === 4 && <><Text style={styles.success}>✓</Text><Heading size="small">Your progress is still here.</Heading><Body muted>{outcome === "relapse" ? "Your streak restarted, while historical progress remains preserved." : "You recorded a recovery event. That awareness compounds."}</Body><Button onPress={() => router.back()}>Return to home</Button></>}</Card></Container></Screen>;
}
const styles = StyleSheet.create({ container: { paddingTop: spacing.xl }, top: { marginBottom: spacing.lg }, card: { paddingVertical: spacing.xl }, intensity: { color: colors.accent, fontSize: 72, fontWeight: "800", marginVertical: spacing.lg }, outOf: { color: colors.muted, fontSize: 22 }, scale: { flexDirection: "row", flexWrap: "wrap", marginBottom: spacing.md }, chips: { flexDirection: "row", flexWrap: "wrap", marginVertical: spacing.lg }, success: { color: colors.accent, fontSize: 60, fontWeight: "800", marginBottom: spacing.md } });
