import { Link } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { Body, Button, Card, Container, Eyebrow, Heading, Screen } from "@/components/ui";
import { useRecovery } from "@/context/RecoveryContext";
import { colors, spacing } from "@/theme";

export default function CalendarScreen() { const { state } = useRecovery(); const now = new Date(); const year = now.getFullYear(); const month = now.getMonth(); const first = new Date(year, month, 1).getDay(); const days = new Date(year, month + 1, 0).getDate(); const has = (day: number, type: "check" | "urge" | "relapse") => { const date = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`; return type === "check" ? state.checkIns.some((item) => item.date === date) : type === "urge" ? state.urges.some((item) => item.occurredAt.slice(0, 10) === date) : state.relapses.some((item) => item.occurredAt.slice(0, 10) === date); }; return <Screen><Container><View style={styles.header}><View><Eyebrow>Recovery calendar</Eyebrow><Heading>{now.toLocaleString(undefined, { month: "long", year: "numeric" })}</Heading></View><Link href="/check-in" asChild><Button variant="secondary">Check in</Button></Link></View><Card><View style={styles.week}><Text style={styles.weekText}>S</Text><Text style={styles.weekText}>M</Text><Text style={styles.weekText}>T</Text><Text style={styles.weekText}>W</Text><Text style={styles.weekText}>T</Text><Text style={styles.weekText}>F</Text><Text style={styles.weekText}>S</Text></View><View style={styles.grid}>{Array.from({ length: first + days }, (_, index) => { const day = index - first + 1; return <View key={index} style={styles.day}>{day > 0 ? <><Text style={[styles.dayNumber, day === now.getDate() && styles.today]}>{day}</Text><View style={styles.dots}><View style={[styles.dot, has(day, "check") && styles.check]} /><View style={[styles.dot, has(day, "urge") && styles.urge]} /><View style={[styles.dot, has(day, "relapse") && styles.relapse]} /></View></> : null}</View>; })}</View><View style={styles.legend}><Legend color={colors.success} label="Check-in" /><Legend color={colors.warning} label="Urge" /><Legend color={colors.danger} label="Relapse" /></View></Card><Card><Eyebrow>How to read this</Eyebrow><Body muted>Calendar marks are records, not judgments. Select a day in the next iteration to inspect its full daily detail.</Body></Card></Container></Screen>; }
function Legend({ color, label }: { color: string; label: string }) { return <View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: color }]} /><Text style={styles.legendText}>{label}</Text></View>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, week: { flexDirection: "row", marginBottom: spacing.sm }, weekText: { flex: 1, textAlign: "center", color: colors.subtle, fontSize: 12, fontWeight: "700" }, grid: { flexDirection: "row", flexWrap: "wrap" }, day: { width: `${100 / 7}%`, aspectRatio: 1, alignItems: "center", justifyContent: "center", borderWidth: 0.5, borderColor: colors.border }, dayNumber: { color: colors.ink, fontSize: 14 }, today: { color: colors.accent, fontWeight: "900" }, dots: { flexDirection: "row", gap: 3, marginTop: 7 }, dot: { width: 5, height: 5, borderRadius: 3, backgroundColor: colors.border }, check: { backgroundColor: colors.success }, urge: { backgroundColor: colors.warning }, relapse: { backgroundColor: colors.danger }, legend: { flexDirection: "row", gap: spacing.md, marginTop: spacing.lg }, legendItem: { flexDirection: "row", alignItems: "center", gap: 5 }, legendDot: { width: 7, height: 7, borderRadius: 4 }, legendText: { color: colors.muted, fontSize: 12 } });
