import { Link } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { Body, Button, Card, Container, Eyebrow, Heading, Screen, Stat } from "@/components/ui";
import { useRecovery } from "@/context/RecoveryContext";
import { averageMood, formatDate } from "@/lib/recovery";
import { colors, spacing } from "@/theme";

export default function CheckInsScreen() { const { state } = useRecovery(); const average = averageMood(state.checkIns); return <Screen><Container><View style={styles.header}><View><Eyebrow>Daily awareness</Eyebrow><Heading>Check-ins</Heading><Body muted>Consistency creates a clearer picture of your recovery.</Body></View><Link href="/check-in" asChild><Button>Check in +</Button></Link></View><View style={styles.stats}><Card style={styles.stat}><Stat label="Total check-ins" value={state.checkIns.length} /></Card><Card style={styles.stat}><Stat label="Average mood" value={average ? average.toFixed(1) : "-"} detail="out of 5" /></Card></View><Card><Eyebrow>History</Eyebrow>{state.checkIns.length === 0 ? <Body muted>No check-ins yet. Your first one takes less than a minute.</Body> : state.checkIns.map((checkIn) => <View style={styles.row} key={checkIn.id}><View style={styles.flex}><Text style={styles.date}>{formatDate(checkIn.date, state.profile.timezone)}</Text><Text style={styles.title}>Mood {checkIn.mood}/5 · Energy {checkIn.energy}/5 · Urge {checkIn.urgeLevel}/10</Text><Text style={styles.meta}>{checkIn.triggers.join(", ") || "No triggers selected"}</Text></View><Text style={styles.confidence}>Confidence {checkIn.confidence}/5</Text></View>)}</Card></Container></Screen>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: spacing.md }, stats: { flexDirection: "row", gap: spacing.md, marginTop: spacing.md }, stat: { flex: 1 }, row: { borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: spacing.md, flexDirection: "row", alignItems: "center" }, flex: { flex: 1 }, date: { color: colors.accent, fontSize: 12 }, title: { color: colors.ink, fontWeight: "700", marginTop: 4 }, meta: { color: colors.muted, fontSize: 12, marginTop: 3 }, confidence: { color: colors.muted, fontSize: 12 } });
