import { useState } from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import { Button, Card, Container, Eyebrow, Field, Heading, Screen, Body } from "@/components/ui";
import { useRecovery } from "@/context/RecoveryContext";
import { supabase } from "@/lib/supabase";
import { colors, spacing } from "@/theme";

const suggestions = ["Analyze my week.", "I'm having an urge.", "Help me plan tonight.", "What patterns are you noticing?"];
export default function CoachScreen() { const { streak, score, phase, stats, state } = useRecovery(); const [message, setMessage] = useState(""); const [reply, setReply] = useState(""); const [loading, setLoading] = useState(false); const send = async (prompt = message) => { if (!prompt.trim()) return; setLoading(true); setReply(""); if (!supabase) { setReply("Connect Supabase to use the private AI coach. Your recovery records remain available locally while the service is unavailable."); setLoading(false); return; } const { data, error } = await supabase.functions.invoke("ai-chat", { body: { message: prompt, storeConversation: state.profile.aiStorageEnabled === true, aiStorageEnabled: state.profile.aiStorageEnabled === true, context: { streak, score, phase: phase.name, recentMood: state.checkIns[0]?.mood ?? null, urgeCount: stats.total } } }); setReply(error ? "The AI coach is temporarily unavailable. Your existing progress is unaffected." : data?.message ?? "The coach returned no message."); setLoading(false); setMessage(""); }; return <Screen><Container><Eyebrow>Private coaching</Eyebrow><Heading>AI Coach</Heading><Body muted>Calm, practical support routed through a server-side safety layer. This is not medical or emergency care.</Body><Card><View style={styles.promptGrid}>{suggestions.map((prompt) => <Button key={prompt} variant="secondary" onPress={() => send(prompt)}>{prompt}</Button>)}</View><Field label="Message" placeholder="What would help right now?" value={message} onChangeText={setMessage} multiline /><Button onPress={() => send()} disabled={loading}>{loading ? <ActivityIndicator color={colors.black} /> : "Send to coach"}</Button></Card>{loading && <Card><Text style={styles.typing}>Coach is thinking...</Text></Card>}{reply ? <Card style={styles.reply}><Eyebrow>Coach response</Eyebrow><Text style={styles.replyText}>{reply}</Text></Card> : <Card style={styles.empty}><Text style={styles.emptyMark}>✦</Text><Heading size="small">A useful conversation starts with context.</Heading><Body muted>Try describing the next hour rather than solving your entire recovery at once.</Body></Card>}</Container></Screen>; }
const styles = StyleSheet.create({ promptGrid: { gap: spacing.sm, marginBottom: spacing.md }, typing: { color: colors.accent }, reply: { borderColor: "#42633A" }, replyText: { color: colors.ink, fontSize: 16, lineHeight: 26 }, empty: { alignItems: "center", paddingVertical: spacing.xl }, emptyMark: { color: colors.accent, fontSize: 40, marginBottom: spacing.md } });
