import { Link } from "expo-router";
import { useMemo, useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";
import { Body, Button, Card, Container, Eyebrow, Field, Heading, Screen } from "@/components/ui";
import { useRecovery } from "@/context/RecoveryContext";
import { formatDate } from "@/lib/recovery";
import { colors, spacing } from "@/theme";

export default function JournalScreen() { const { state, deleteJournal } = useRecovery(); const [query, setQuery] = useState(""); const entries = useMemo(() => state.journalEntries.filter((entry) => `${entry.title} ${entry.content} ${entry.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [state.journalEntries, query]); return <Screen><Container><View style={styles.header}><View><Eyebrow>Private space</Eyebrow><Heading>Journal</Heading><Body muted>Your entries stay private and are stored locally until you connect a backend.</Body></View><Link href="/journal/new" asChild><Button>New entry +</Button></Link></View><Field label="Search entries" placeholder="Search by title, note, or tag" value={query} onChangeText={setQuery} />{entries.length === 0 ? <Card style={styles.empty}><Text style={styles.emptyMark}>◌</Text><Heading size="small">{query ? "No matching entries" : "Make space to notice."}</Heading><Body muted>{query ? "Try a different search term." : "A few honest lines can turn a difficult moment into useful information."}</Body>{!query && <Link href="/journal/new" asChild><Button variant="secondary">Write your first entry</Button></Link>}</Card> : entries.map((entry) => <Card key={entry.id}><View style={styles.row}><View style={styles.flex}><Text style={styles.date}>{formatDate(entry.createdAt, state.profile.timezone)} {entry.mood ? `· mood ${entry.mood}/5` : ""}</Text><Heading size="small">{entry.title}</Heading><Body muted>{entry.content.length > 180 ? `${entry.content.slice(0, 180)}...` : entry.content}</Body><Text style={styles.tags}>{entry.tags.map((tag) => `#${tag}`).join("  ")}</Text></View><Button variant="ghost" onPress={() => Alert.alert("Delete entry?", "This private entry will be permanently removed.", [{ text: "Cancel" }, { text: "Delete", style: "destructive", onPress: () => deleteJournal(entry.id) }])}>Delete</Button></View></Card>)}</Container></Screen>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: spacing.md, gap: spacing.md }, flex: { flex: 1 }, row: { flexDirection: "row", gap: spacing.sm }, date: { color: colors.accent, fontSize: 12, marginBottom: spacing.sm }, tags: { color: colors.muted, fontSize: 12, marginTop: spacing.md }, empty: { alignItems: "center", paddingVertical: spacing.xxl, marginTop: spacing.md }, emptyMark: { color: colors.accent, fontSize: 48, marginBottom: spacing.md } });
