import { StyleSheet, Text, View } from "react-native";
import { Body, Button, Card, Container, Eyebrow, Heading, Screen } from "@/components/ui";
import { useRecovery } from "@/context/RecoveryContext";
import { RECOVERY_PROGRAMS } from "@/lib/programs";
import { colors, spacing } from "@/theme";

export default function RecoveryScreen() {
  const { state, activateProgram, completeProgramDay } = useRecovery();
  const active = RECOVERY_PROGRAMS.find((program) => program.id === state.activeProgramId);
  const progress = active ? state.programProgress[active.id] ?? [] : [];
  return <Screen><Container><Eyebrow>Structured practice</Eyebrow><Heading>Recovery programs</Heading><Body muted>Choose a pace that supports your life. Programs are guides, not tests.</Body>{active ? <Card style={styles.active}><View style={styles.row}><View style={styles.flex}><Eyebrow>Active program</Eyebrow><Heading size="medium">{active.name}</Heading><Body muted>{active.description}</Body></View><Text style={styles.percent}>{Math.round((progress.length / active.duration) * 100)}%</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${Math.min(100, (progress.length / active.duration) * 100)}%` }]} /></View>{active.days.slice(0, 7).map((day) => <View style={styles.day} key={day.day}><View style={[styles.dayDot, progress.includes(day.day) && styles.dayDone]}><Text style={styles.dayDotText}>{progress.includes(day.day) ? "✓" : day.day}</Text></View><View style={styles.flex}><Text style={styles.dayTitle}>{day.title}</Text><Text style={styles.dayExercise}>{day.exercise}</Text></View><Button variant={progress.includes(day.day) ? "ghost" : "secondary"} onPress={() => completeProgramDay(active.id, day.day)}>{progress.includes(day.day) ? "Done" : "Complete"}</Button></View>)} </Card> : null}{RECOVERY_PROGRAMS.filter((program) => program.id !== active?.id).map((program) => <Card key={program.id}><View style={styles.row}><View style={styles.flex}><Text style={styles.kicker}>{program.duration} days · {program.focus}</Text><Heading size="small">{program.name}</Heading><Body muted>{program.description}</Body></View><Button variant="secondary" onPress={() => activateProgram(program)}>Start</Button></View></Card>)}</Container></Screen>;
}

const styles = StyleSheet.create({ active: { borderColor: "#42633A" }, row: { flexDirection: "row", alignItems: "flex-start", gap: spacing.md }, flex: { flex: 1 }, percent: { color: colors.accent, fontSize: 24, fontWeight: "800" }, track: { height: 7, backgroundColor: colors.border, borderRadius: 4, overflow: "hidden", marginVertical: spacing.lg }, fill: { height: "100%", backgroundColor: colors.accent }, day: { flexDirection: "row", alignItems: "center", gap: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: spacing.md }, dayDot: { width: 30, height: 30, borderRadius: 15, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" }, dayDone: { backgroundColor: colors.accent, borderColor: colors.accent }, dayDotText: { color: colors.ink, fontSize: 12, fontWeight: "700" }, dayTitle: { color: colors.ink, fontWeight: "700", fontSize: 14 }, dayExercise: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 2 }, kicker: { color: colors.accent, fontSize: 12, fontWeight: "700", marginBottom: 5 } });
