import { Link } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { Body, Button, Card, Container, Eyebrow, Heading, Screen, Stat } from "@/components/ui";
import { useRecovery } from "@/context/RecoveryContext";
import { formatDate } from "@/lib/recovery";
import { colors, spacing } from "@/theme";

export default function UrgesScreen() { const { state, stats } = useRecovery(); return <Screen><Container><View style={styles.header}><View><Eyebrow>Pattern tracking</Eyebrow><Heading>Urges</Heading><Body muted>Record what happened without turning a moment into an identity.</Body></View><Link href="/urge/new" asChild><Button>Log urge +</Button></Link></View><View style={styles.stats}><Card style={styles.stat}><Stat label="Total" value={stats.total} /></Card><Card style={styles.stat}><Stat label="Defeated" value={stats.defeated} /></Card><Card style={styles.stat}><Stat label="Average intensity" value={stats.averageIntensity.toFixed(1)} /></Card><Card style={styles.stat}><Stat label="Defeat rate" value={`${stats.defeatPercentage}%`} /></Card></View><Card><Eyebrow>Recent events</Eyebrow>{state.urges.length === 0 ? <Body muted>No urges logged yet. SOS mode is the fastest way to start.</Body> : state.urges.map((urge) => <View style={styles.row} key={urge.id}><View style={styles.flex}><Text style={styles.date}>{formatDate(urge.occurredAt)} · {urge.intensity}/10</Text><Text style={styles.title}>{urge.trigger}</Text><Text style={styles.meta}>{urge.actionTaken || "No action recorded"}</Text></View><Text style={[styles.outcome, urge.outcome === "relapse" && styles.relapse]}>{urge.outcome}</Text></View>)}</Card></Container></Screen>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: spacing.md }, stats: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md, marginTop: spacing.md }, stat: { flex: 1, minWidth: 140 }, row: { borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: spacing.md, flexDirection: "row", alignItems: "center" }, flex: { flex: 1 }, date: { color: colors.accent, fontSize: 12 }, title: { color: colors.ink, fontWeight: "700", marginTop: 4 }, meta: { color: colors.muted, fontSize: 12, marginTop: 3 }, outcome: { color: colors.success, fontSize: 12, fontWeight: "700" }, relapse: { color: colors.warning } });
